config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users
  resources :designers
  resources :synths
  resources :bands

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id          :bigint(8)        not null, primary key
#  name        :text
#  year_formed :integer
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Band < ApplicationRecord
  has_and_belongs_to_many :synths, join_table: "bands_synths"
end

app/models/designer.rb
# == Schema Information
#
# Table name: designers
#
#  id         :bigint(8)        not null, primary key
#  name       :text
#  dob        :text
#  company    :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Designer < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :synths
end

app/models/synth.rb
# == Schema Information
#
# Table name: synths
#
#  id          :bigint(8)        not null, primary key
#  name        :text
#  voices      :integer
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  designer_id :integer
#

class Synth < ApplicationRecord
  belongs_to :designer, :optional => true
  has_and_belongs_to_many :bands, join_table: "bands_synths"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :text
#  password_digest :text
#  admin           :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  has_one :designer
  validates :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  require 'rspotify'
  before_action :authenticate

  def index
    @bands = Band.all
  end
  def show
    @band = Band.find params[:id]
    artists = RSpotify::Artist.search("#{@band.name}", limit: 1, market: 'US')
    @artist = artists.first
  end
  def new
    @band = Band.new
  end
  def create
    band = Band.create band_params
    redirect_to band_path(band.id)
  end
  def edit
    @band = Band.find params[:id]
  end
  def update
    band = Band.find params[:id]
    band.update band_params
    redirect_to band_path(band.id)
  end
  def destroy
    band = Band.find params[:id]
    band.destroy
    redirect_to bands_path
  end
  private
  def authenticate
    RSpotify::authenticate("517599d3dfd54407a8285bec2c65ea68", "fc35556269234c43a9c6451320b9a605")
  end
  def band_params
    params.require(:band).permit(:name, :year_formed, :image, :synth_ids => [])
  end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  def index
    @designers = Designer.all
  end

  def show
    @designer = Designer.find params[:id]
  end

  def create
    designer = Designer.create designer_params
    # these two lines are included to create association between user and the designer creating them
    designer.user_id = @current_user.id
    designer.update designer_params
    redirect_to designer_path(designer.id)
  end

  def new
    @designer = Designer.new
  end

  def edit
    @designer = Designer.find params[:id]
  end

  def update
    designer = Designer.find params[:id]
    # user id excepted here to stop different users or admin from changing user id inadvertantly
    designer.update designer_params.except(:user_id)
    redirect_to designer_path(designer.id)
  end

  def destroy
    designer = Designer.find params[:id]
    designer.destroy
    redirect_to designers_path
  end

  private
  def designer_params
    params.require(:designer).permit(:name, :dob, :company, :image, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.new
    @designer = Designer.find_by :user_id => session[:user_id]
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/synths_controller.rb
class SynthsController < ApplicationController
  def index
    @synths = Synth.all
  end
  def show
    @synth = Synth.find params[:id]
    if @synth.designer_id.present?
      @designer = Designer.find @synth.designer_id
    end
  end
  def new
    @synth = Synth.new
  end
  def create
    synth = Synth.create synth_params
    redirect_to synth_path(synth.id)
  end
  def edit
    @synth = Synth.find params[:id]
  end
  def update
    synth = Synth.find params[:id]
    synth.update synth_params
    redirect_to synth_path(synth.id)
  end
  def destroy
    synth = Synth.find params[:id]
    synth.destroy
    redirect_to synths_path
  end
  private
  def synth_params
    params.require(:synth).permit(:name, :voices, :image, :designer_id, :band_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/synths_helper.rb
module SynthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/_form.html.erb
<%= form_for @band do |f| %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true, :required => true, :class => 'form-control col-6' %>
  </div>

  <div class="form-group">
  <%= f.label :year_formed, "Year Formed" %>
  <%= f.text_field :year_formed, :class => 'form-control col-6' %>
  </div>

  <div class="form-group">
  <%= f.label :image, "Band Photo" %>
  <%= f.url_field :image, :class => 'form-control col-6' %>
  </div>

  <div class="form-group">
    <%= f.label :band_ids, "Select any synths that this band has used" %>
    <br>
    <%= hidden_field_tag "band[synth_ids][]", nil %>
    <% Synth.order(:name).each do |synth| %>
      <%= check_box_tag "band[synth_ids][]", synth.id,
      @band.synth_ids.include?(synth.id), :id => dom_id(synth)%>
      <%= label_tag dom_id(synth), synth.name %><br>
    <% end %>
  </div>

  <%= f.submit "Submit", :class => 'btn btn-primary' %>
<% end %>

app/views/bands/edit.html.erb
<h2>Edit Band</h2>

<%= render :partial => 'form' %>

<br>

app/views/bands/index.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <h1>Bands</h1>
    <%= link_to 'Add New Band', new_band_path, :class => "btn btn-primary" %>
    <br>
    <br>
    <% @bands.order(:name).each do |band| %>
    <%= image_tag band.image, :class => 'img-thumbnail img-responsive' %>

    <ul>
      <br>
      <li>
        Name: <%= link_to band.name, band_path(band.id) %>
      </li>
      <li>
        Year Formed: <%= band.year_formed %>
      </li>
    </ul>
    <br>
    <% end %>
  </div>

</div>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render :partial => 'form' %>

<br>

app/views/bands/show.html.erb
<div class="col-8">

  <h1><%= @band.name %></h1>

  <%= image_tag @band.image, :alt => @band.name, :class => 'rounded mx-auto d-block img-thumbnail img-responsive' %>

  <ul>

    <li>
      <h4>Name:</h4> <%= link_to @band.name, band_path(@band.id) %>
    </li>

    <li>
      <h4>Year Formed:</h4> <%= @band.year_formed %>
    </li>

    <li>
      <h4>Top Tracks:</h4>
      <% @artist.top_tracks(:AU).each do |track| %>
      <ol><%= track.name %></ol>
      <% end %>
    </li>

    <li>
      <h4>Albums available on Spotify:</h4>
      <% @artist.albums(album_type: 'album', market: 'US').each do |album| %>
      <p><%= album.name %></p>
      <ol>
        Released: <%= album.release_date %>
      </ol>
      <% end %>
    </li>

    <li>
      <h4>Genres:</h4>
      <% @artist.genres.each do |genre| %>
      <ol><%= genre.capitalize %></ol>
      <% end %>
    </li>

    <div class="col-10">
      <li>
        <h4>Synths Used</h4>
        <ol>

          <% @band.synths.each do |synth| %>
          <%= synth.name %>

          <%= link_to image_tag(synth.image, :class => 'img-thumbnail img-fluid'), synth %>
          <% end %>
        </ol>
      </li>
    </div>

  </ul>

  <div class="controls">
    <%= link_to "Edit Band", edit_band_path(@band), :class => 'btn btn-primary'  %>
    <%= link_to "Delete Band", band_path(@band), :method => 'delete', :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-primary'  %>
  </div>
  <br>
</div>

app/views/designers/_form.html.erb
<%= form_for @designer do |f| %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true, :required => true, :class => 'form-control col-6'%>
  </div>

  <div class="form-group">
  <%= f.label :dob, "Date of Birth" %>
  <%= f.text_field :dob, :class => 'form-control col-6' %>
  </div>

  <div class="form-group">
  <%= f.label :company, "Company" %>
  <%= f.text_field :company, :class => 'form-control col-6' %>
  </div>

  <div class="form-group">
  <%= f.label :image, "Photo" %>
  <%= f.url_field :image, :class => 'form-control col-6', :placeholder => 'Paste an image URL' %>
  </div>

  <%= f.submit "Submit", :class => 'btn btn-primary'%>
<% end %>

app/views/designers/edit.html.erb
<h1>Edit Designer</h1>

<%= render :partial => 'form' %>

<br>

app/views/designers/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Designers</h1>
    <%= link_to 'Add New Designer', new_designer_path, :class => "btn btn-primary" %>
    <br>
    <br>
    <% @designers.order(:name).each do |designer| %>
    <%= image_tag designer.image, :class => 'img-thumbnail img-responsive' %>
    <ul>
      <br>
      <li>
        Name: <%= link_to designer.name, designer_path(designer.id) %>
      </li>
      <li>
        Date of Birth: <%= designer.dob %>
      </li>
      <li>
        Works at: <%= designer.company %>
      </li>
    </ul>
    <br>
    <% end %>
  </div>

</div>

app/views/designers/new.html.erb
<h1>New Designer</h1>

<%= render :partial => 'form' %>

<br>

app/views/designers/show.html.erb
<div>

  <h1><%= @designer.name %></h1>

  <%= image_tag @designer.image, :alt => @designer.name, :class => 'img-thumbnail img-fluid' %>

  <ul>
    <div class="col-6">
    <li>
      Name: <%= link_to @designer.name, designer_path(@designer.id) %>
    </li>

    <li>
      Date of Birth: <%= @designer.dob %>
    </li>

    <li>
      Works at: <%= @designer.company %>
    </li>
    </div>

    <% if @designer.synths != []%>
      <div class="col-6">
        <li>
          Synthesisers designed by <%= @designer.name %>:
          <ol>
            <% @designer.synths.each do |synth| %>
            <%= synth.name %>
            <%= link_to image_tag(synth.image, :class => 'img-thumbnail img-fluid'), synth %>
            <% end %>
            <br>
          </ol>
        </li>
      </div>
    <% end %>
  </ul>
  <% if @current_user != nil %>
    <% if @current_user.admin? || @designer.user_id == @current_user.id %>
    <div class="controls">
      <%= link_to "Edit Designer", edit_designer_path(@designer), :class => 'btn btn-primary' %>
      <%= link_to "Delete Designer", designer_path(@designer), :method => 'delete', :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-primary'  %>
    </div>
    <% end %>
  <% end %>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sine.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        Sine.
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/designers">Designers</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/synths">Synthesisers</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/bands">Bands</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if @current_user.present? %>
                <% if @current_user.admin? %>
                  <%= link_to "All Users", users_path, :class => "dropdown-item" %>
                <% end %>
                <%= link_to "Account Page", root_path, :class => "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Sign Out #{ @current_user.email }", login_path, :method => 'delete', :class => "dropdown-item" %>
                <% else %>
                  <%= link_to 'Sign Up', new_user_path, :class => "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Sign In', login_path, :class => "dropdown-item" %>
              <% end %>
            </div>

          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

  </body>

</html>

app/views/pages/_form.html.erb
<div>
  <h1>Welcome to Sine.</h1>
  <h1>Sign Up Here</h1>
  <br>
  <%= session[:error] %>

  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control col-6' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control col-6' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation, :class => 'form-control col-6' %>
  </div>
  <%= f.submit "Sign Up", :class => 'btn btn-primary' %>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="col-6">
  <% if @current_user.present? %>
  <h2>Welcome, <%= @current_user.email %>! </h2>

    <% if @designer != nil %>
      <%= image_tag @designer.image, :alt => @designer.name, :class => 'img-thumbnail img-fluid' %>
    <% end %>

    <br>
    <br>

    <% if @designer != nil %>
      <%= link_to "Go To Your Profile", designer_path(@designer), :class => 'btn btn-primary' %>

      <%= link_to "Edit Your Profile", edit_designer_path(@designer), :class => 'btn btn-primary' %>
    <% end %>

  <% if @designer == nil %>
    <%= link_to "Create Your Profile", new_designer_path(@designer), :class => 'btn btn-primary' %>
  <% end %>

  <%= link_to "Delete your Account", user_path(@current_user), :method => 'delete', :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-primary'  %>

  <% else %>
    <%= render :partial => 'form' %>
    <br>
    Already have an account?
    <%= link_to 'Sign in here', login_path %>
  <% end %>
</div>
<br>

app/views/session/new.html.erb
<h1>Sign In</h1>

<%= session[:error] %>



<%= form_tag login_path do %>

  <div class="form-group">
  <%= label_tag :email %>
  <%= email_field_tag :email, nil, :class => "form-control col-6" %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, :class => "form-control col-6"  %>
  </div>
  <div class="form-group">
    <%= submit_tag "Sign In", :class => "btn btn-primary"%>
  </div>
  <br>
<% end %>

app/views/synths/_form.html.erb
<%= form_for @synth do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :autofocus => true, :required => true, :class => 'form-control col-6' %>
  </div>

  <div class="form-group">
    <%= f.label :voices, "Voice Count" %>
    <%= f.number_field :voices, :class => 'form-control col-6'  %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Photo" %>
    <%= f.url_field :image, :class => 'form-control col-6', :placeholder => 'Paste an image URL' %>
  </div>

  <div class="form-group">
    <%= f.label :designer_id, "Synth Designer" %>
    <%= f.select :designer_id, Designer.pluck(:name, :id), :include_blank => true, :required => true, :class => 'form-control col-6'  %>
  </div>

  <div class="form-group">
    <%= f.label :band_ids, "Select a band that has used this synth" %>
    <br>
    <%= hidden_field_tag "synth[band_ids][]", nil %>
    <% Band.order(:name).each do |band| %>
      <%= check_box_tag "synth[band_ids][]", band.id,
      @synth.band_ids.include?(band.id), :id => dom_id(band)%>
      <%= label_tag dom_id(band), band.name %><br>
    <% end %>
  </div>

  <%= f.submit "Submit", :class => 'btn btn-primary' %>
<% end %>

app/views/synths/edit.html.erb
<h1>Edit Synthesiser</h1>

<%= render :partial => 'form' %>

<br>

app/views/synths/index.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-4">
    <h1>Synthesisers</h1>

    <%= link_to 'Add New Synthesiser', new_synth_path, :class => "btn btn-primary" %>
    <br>
    <br>
    <% @synths.order(:name).each do |synth| %>

      <%= image_tag synth.image, :class => 'img-thumbnail img-responsive' %>

    <br>
    <ul>
      <li>
        Name: <%= link_to synth.name, synth_path(synth.id) %>
      </li>
    </ul>
    <br>
    <% end %>

  </div>

</div>

app/views/synths/new.html.erb
<h1>New Synthesiser</h1>

<%= render :partial => 'form' %>

<br>

app/views/synths/show.html.erb
<div class="col-8">
  <h1><%= @synth.name %></h1>

  <%= image_tag @synth.image, :alt => @synth.name, :class => 'feature' %>

  <ul>
    <li>
      Name: <%= link_to @synth.name, synth_path(@synth.id) %>

    </li>
    <% if @designer.present? %>
    <li>
      Manufacturer: <%= @designer.company %>
    </li>
    <li>
      Designed by: <%= link_to @designer.name, designer_path(@designer) %>
    </li>
    <% end %>
    <li>
      Voice Count: <%= @synth.voices %>
    </li>

  </ul>
  <% if @synth.bands != [] %>
  <div class="col-8">
    Bands that have used this synthesiser:
    <ol>
      <% @synth.bands.each do |band| %>
      <%= band.name %>
      <%= link_to image_tag(band.image, :class => 'img-thumbnail img-responsive'), band %>
      <% end %>
    <ol>
  </div>
  <% end %>

  <div class="controls">
    <%= link_to "Edit Synth", edit_synth_path(@synth), :class => 'btn btn-primary' %>
    <%= link_to "Delete Synth", synth_path(@synth), :method => 'delete', :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-primary' %>
  </div>
  <br>
</div>

app/views/users/index.html.erb
<div>
  <h1>All Users</h1>
  <% @users.each do |user| %>
  <li>
    <%= user.email %>
    <p>
      <%= link_to "Delete User Account", user_path(user), :method => 'delete', :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-primary'  %>
      <% end %>
    </p>
    <br>
  </li>
</div>

app/views/users/new.html.erb
<h1>Welcome to Sine. Sign Up</h1>


<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
<% end %>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control col-6' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control col-6' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation, :class => 'form-control col-6' %>
  </div>
  <%= f.submit "Sign Up", :class => 'btn btn-primary' %>
  <br>
  <br>
<% end %>